backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
site_url: https://nova-warszawazoliborz.netlify.com/
display_url: https://nova-warszawazoliborz.netlify.com/
locale: "pl"

media_folder: static/img
public_folder: /img
logo_url: https://raw.githubusercontent.com/Gregorgeous/nova-2020-public/master/static/img/zoliborz_logo.png

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - { label: "Main layout", value: "MainLayout" }
          - { label: "Sub-page layout", value: "SubPageLayout" }
        default:
          - { label: "Main layout", value: "MainLayout" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      # OR ... (from: https://github.com/thomaswang/gatsby-personal-starter-blog/blob/master/static/admin/config.yml)
      # - { name: path, label: Path }
      # - { name: date, label: Date, widget: date }
      # - { name: title, label: Title }
      # - { name: description, label: Description }
      # - { name: body, label: Body, widget: markdown }
